### ISSUE TITLE
load image from buffer

### ISSUE THREAD

**Issue by schmurfy** [clearscene/pHash#6]
I wasn't able to find a way to load an image from a buffer (where the file was previously loaded) instead of directly from the file, is there anything somewhere or is it a limitation of the library (or of a dependency) ?

**Comment by MrSapps** [comment]
I'm assuming there is still no way to do this?

**Comment by glowkeeper** [comment]
+1 on buffered load. Slightly concerned that the maintenance of pHash seems a bit defunct :(

**Comment by nsant061** [comment]
@paulsapps  @glowkeeper I used CImg library to convert a cv::Mat to CImg file, as it is written in pHash.cpp
Old method: 
`int ph_dct_imagehash(const char* file,ulong64 &hash){
    if (!file){
	return -1;
    }
    CImg<uint8_t> src;
    try {
	src.load(file);
    } catch (CImgIOException ex){
	return -1;
    }`

New method:
`int ph_dct_imagehash(cv::Mat& file,ulong64 &hash){
  CImg<uint8_t> src;
  try {
    //Convert cv::Mat to CImg.
    src = CImg<uint8_t>(file);
  } catch (CImgIOException ex){
    return -1;
  }`

You will need to use CImg.h and cvMat.h to compile this. 
Reference I used : [CImg Library](https://github.com/dtschump/CImg/blob/master/plugins/cvMat.h)
Hope this helps.
