### ISSUE TITLE
Project Ownership

### ISSUE THREAD

**Issue by clearscene** [clearscene/pHash#9]
Hi,
I'd like to take ownership of this project.
I use pHash in one of my projects and have found that, because of it's inactivity Debian has dropped it from the repositories. I'm starting the process of getting it accepted again, but will need a git-repo to work from. For that I may was well use the closest thing to a canonical repo - which is this.
Any concerns/questions, do let me know.
Cheers.

**Comment by sdepold** [comment]
Sure! I have to say that I'm not a maintainer or even contributor at all. But you can totally become a maintainer. I will update the repo tomorrow. We can also transfer it to your account

**Comment by clearscene** [comment]
That's great. Cheers.

I've been in contact with the original authors of pHash, and they have confirmed that the project does not have a public code repo (only tar.gz snapshots).

I'm planning on getting the most current version merged in, and fixing the issues raised by Debian, in order to get it re-included into the Debian repositories. 

So the status of this repo is fine (I'd rather work from something that has some traction in the community, rather than starting from a fresh repo). Am happy to take this repo into my account.

Cheers.

**Comment by sdepold** [comment]
I requested the transfer.

**Comment by clearscene** [comment]
Thank you
